### PR TITLE
Added support for passing theme to functions in array css prop

### PR DESCRIPTION
**Pull request by jtmthf**
**What**: When passing an array to the css-prop, functions accepting the theme from `emotion-theming` are now acceptable as array items.

**Why**: This addresses #997. I find that there are many use cases where this is helpful. One example would be when composing a number of style utility functions that may or may not read from the theme. For my use case in particular, I'm working on a reimplementation of [Tailwind CSS](https://tailwindcss.com) using emotion. This is what one example of usage looks like right now.

```jsx
<div
  css={theme => [
    display('flex')
    bg('white')(theme),
    mx("auto")(theme),
    maxW('sm')(theme),
    shadow('lg')(theme),
    rounded('lg')(theme),
    { overflow: "hidden" }
  ]}
/>
```

With this change, the example can be rewritten as:

```jsx
<div
  css={[
    display('flex')
    bg('white'),
    mx("auto"),
    maxW('sm'),
    shadow('lg')
    rounded('lg'),
    { overflow: "hidden" }
  ]}
/>
```

In addition to being shorter, the advantage here is that the developer doesn't need to know if a value in the css-prop is a function that needs to be passed the theme.

**How**: The change was implemented by now wrapping all uses of the array css prop in `ThemeContext.Consumer`. It could potentially be more optimized to check if the array contains a function first before wrapping in the consumer. In the render method, if the css prop is an array, it is now mapped and for each item that is an array it is passed the theme.

**Checklist**:
- [ ] Documentation
- [x] Tests
- [x] Code complete
- [ ] TypeScript typings

### CODE REVIEW

**Comment by luishdz1010** [comment]
This would be truly helpful, right now object styles break encapsulation since you need to know whether they are functions or objects

**Comment by jtmthf** [comment]
@simonflk I actually have the feature you described implemented locally, but not yet committed to this branch. I still need to add documentation and TypeScript typings, but am holding off until I get confirmation that this is something the project owner's want.

**Comment by chibicode** [comment]
👍 This is exactly what I need! Would love to see this merged.

**Comment by a-type** [comment]
I'd love to see this as well. It's critical to a project I'm working on where I want to be able to compose in user-provided styles and allow the ability to utilize the theme.

**Comment by jckw** [comment]
Would be amazing to get this merged! Any timeline?

**Comment by Andarist** [comment]
I got this working, made additional changes to babel plugin and Global's styles prop (so its behavior match css prop). I think it's done and would consider it a good change overall - still need @mitchellhamilton approval though.

**Pull request merged**
