### PR TITLE
Feat: generate bundles for "worker" style environement

### PR DESCRIPTION
**Pull request by nicksrandall**
**What**:

This is PR uses a ~~*hopefully* soon-to-be-released~~ newly released version of preconstruct that support building "worker" compatible builds. The primary use-case for this is to support Cloudflare workers. 

**Why**:
See #2554 

**How**:
I've made changes to each package in the monorepo and extended the package.json to include an "exports" field with custom conditionals for "browser" and "worker". 

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Code complete
- [ ] Changeset

### CODE REVIEW

**Comment by ItsWendell** [comment]
This is also super relevant for the Next.js Edge Runtime now (which is essentially built Cloudflare Worker): https://github.com/emotion-js/emotion/issues/2777, https://github.com/emotion-js/emotion/issues/2554

**Comment by nicksrandall** [comment]
@mitchellhamilton @Andarist I have updated this PR to use the new v2.1.8 version of preconstruct and attempted to build with the new "worker" condition enabled but I must be missing something because that specific condition is not being generated. (The browser conditions is working). Any chance you could take a quick look and let me know what I did wrong?

**Comment by mitchellhamilton** [comment]
`envConditoins` should be `envConditions`. Also, could you remove browser & worker builds for things that don't use `typeof window` or etc. (e.g. `memoize` but there are some others it looks like). Also, could you set `preconstruct.exports` to true at the root level so there should only be `preconstruct.exports` config on packages that need worker & browser builds.

**Comment by nicksrandall** [comment]
Didn't mean to close, re-created in #2819

**Pull request closed without merging**
