### PR TITLE
Add link of stylelint

### PR DESCRIPTION
**Pull request by gucong3000**
**What**:
Adds stylelint link to README Ecosystem section

**Why**:
Because Emotion users maybe want to lint their CSS code.

**How**:
I updated the README with text

**Checklist**:

- [x] Documentation
- [ ] Tests
- [ ] Code complete

Closes: #185 #686

### CODE REVIEW

**Comment by tkh44** [comment]
Thanks

**Comment by lydell** [comment]
Hi! I'm new to emotion and saw that link – but now I'm just confused. How do I use stylelint with emotion exactly?

**Comment by Ailrun** [comment]
@lydell As far as I know, you can use it with
1. https://github.com/gucong3000/postcss-jsx
Though IDK it works well or not.

**Comment by lydell** [comment]
Cool, thanks! That should have been linked to as well…

**Pull request merged**
