### PR TITLE
Add type for `as` prop on styled components

### LINKED ISSUE #1137: `as` prop of styled components in TypeScript
- `emotion` version: 10.0.5
- `react` version: 16.6.3

**Relevant code:**

```typescript
// Custom styled function that is typed with my theme interface
import styled, { CreateStyled } from '@emotion/styled'

import { ITheme } from '../theme'

export default styled as CreateStyled<ITheme>

// Style function interface in a Util module
declare module 'Util' {
  import { css } from '@emotion/core'
  import { ITheme } from '../util/theme'

  type CssType = typeof css

  export interface IStyleFunction<P = {}> {
    ( arg0: { theme: ITheme } & P): ReturnType<CssType> | false | null
  }
}

// Component code
type HeadingProps = {
  size?: FontSizes
}

const baseStyles: IStyleFunction<HeadingProps> = ({ theme }) => css`
  font-family: ${theme.fonts.heading};
`

const sizeStyles: IStyleFunction<HeadingProps> = ({
  theme,
  size = 'regular',
}) => {
  const [defaultSize, smallBreakPoint] = fontSizes[size]

  return css`
    font-size: ${theme.fontSizes[defaultSize]};

    ${theme.mq[0]} {
      font-size: ${theme.fontSizes[smallBreakPoint]};
    }
  `
}

const Heading = styled.h3<HeadingProps>(baseStyles, sizeStyles)

// Using the component
<Heading as="h5" size="tiny">
  This is an important heading
</Heading>
```

**What you did:**

- Set up a Next js project with Typescript in strict mode
- Use Emotion 10
- Using a customized `styled` function
- Using the `ThemeProvider`
- Create a styled component and pass the component props as `ExtraProps` to the styled function
- When using the styled component pass the `as` prop from Emotion 10 to change the element being used.

**What happened:**

Typescript complains about the `as` prop not existing on the styled component

screenshot 2018-12-28 at 10 56 05

**Reproduction:**

I've created a code sandbox for this, but I don't think the setup there properly reflects mine. Since you can't seem to customize the tsconfig in the default Typescript + React starter, I don't know what else to do. In any case code sandbox does not show any typescript errors.

https://codesandbox.io/s/mzyzm524lj

**Problem description:**

I would like to not get compiler warnings about the `as` prop. If I add `as` to my component's `ExtraProps` (in the above example the `HeadingProps`), the compiler stops complaining.

Thanks a lot for the help. I love emotion and I've been using it for about a year now. Just new to the whole TypeScript thing. 😅

### PR DESCRIPTION
**Pull request by connor-baer**
Closes #1137.

**What**: Add basic type for the `as` prop on styled components.

**Why**: If I add `as` to my component's `ExtraProps` the TypeScript compiler complains about the `as` prop not existing on the styled component (see #1137 for a full reproduction).

**How**: Add the `as` prop to the `CreateStyled` instance in `packages/styled/types/base.d.ts`

**Checklist**:

- [ ] Documentation
- [x] Tests
- [x] Code complete
- [x] Changeset

### CODE REVIEW

**Comment by connor-baer** [comment]
This is my first time contributing to Emotion. I have a couple of questions: 

1. How do I know which packages to include in the changeset? Do I only bump the package I changed (`@emotion/styled`) and `changeset` will bump the packages that depend on it as well?
2. Would this changes to the types be considered a breaking change? Can I backport it to v10?

**Comment by connor-baer** [comment]
Also not sure if I need to add the type on lines [109](https://github.com/emotion-js/emotion/blob/b1e6e13692471b613e798af245ea9b4dba86c472/packages/styled/types/base.d.ts#L109), [114](https://github.com/emotion-js/emotion/blob/b1e6e13692471b613e798af245ea9b4dba86c472/packages/styled/types/base.d.ts#L114), and [123](https://github.com/emotion-js/emotion/blob/b1e6e13692471b613e798af245ea9b4dba86c472/packages/styled/types/base.d.ts#L123) as well.

**Comment by Andarist** [comment]
> How do I know which packages to include in the changeset? Do I only bump the package I changed (@emotion/styled) and changeset will bump the packages that depend on it as well?

Just think about for which packages your changes were relevant - this sometimes might include dependents of a package, but sometimes not. In the case of `@emotion/styled` there are no dependents so there is no problem with deciding that 😉 

> Would this change to the types be considered a breaking change? Can I backport it to v10?

Honestly, I would prefer not to touch v10 at all, and even more so its types as they are somewhat convoluted. I'm in the process of handling all open issues/PRs so we can ship v11 as soon as possible. V11 doesn't include many substantial breaking changes so I hope the migration should be pretty straightforward.

If you manage to backport it to v10 I will consider merging it though (if we decide to merge this one into v11).

---
Sorry for a late review, I'm quite busy and tired lately. 

@JakeGinnivan this doesn't provide super strict typings for `as` prop, but I guess this is fine to merge. WDYT?

**Comment by connor-baer** [comment]
Thanks for the notes @Andarist! I've added the changeset.

I'm okay to only include this in v11. Backporting to v10 doesn't look too difficult though based on @JakeGinnivan's [comment](https://github.com/emotion-js/emotion/issues/1137#issuecomment-630774477), so if others are interested, I'd be happy to take care of that, too.

**Comment by Andarist** [comment]
Sorry that it took so long to merge this. Thank you very much for doing preparing this PR @connor-baer ❤️

**Comment by Andarist** [comment]
I've discovered one flaw of this approach - `as` became available within interpolations when most of the time it shouldn't. Any ideas on how to solve this? The only thing that comes to my mind is adding an additional overload for props that are not meant to be available in interpolations & are not meant to be forwarded by default. This complicates the API - so maybe it's not worth fixing at all? cc @JakeGinnivan

**Pull request merged**
