### PR TITLE
Improve composes docs with workaround for nested selectors

### LINKED ISSUE #137: Improve documentation for composes
*(We've talked about this before, I'm just opening an issue so it stays on my radar, so I can be sure to remember to knock this out first chance I get time for oss this week)* 😄

I'd like to touch just a little bit on the `composes` section of the documentation in order to better cover some pitfalls, like we discussed in slack last week (i.e., since `composes` with a pseudo selector like `&:hover` does not work, here's the suggested pattern...). I think addressing this here will help readers adopt the right patterns for quickly working with emotion effectively.

### PR DESCRIPTION
**Pull request by hawkins**
**What**:

Fixes #137 

**Why**:

So users will see why nested composes won't work, and understand the right pattern to use for this scenario

**How**:

By adding a couple small `css` examples with nested / pseudo-selectors that *will* work, following what *won't* in the docs for `composes`

**Checklist**:

- [x] Documentation
- [ ] Tests N/A
- [x] Code complete

---

I'm opening this PR to discuss the changes a little bit more. This is the example that would have helped me a good bit in understanding how to use emotion when I first started, but I'm curious for y'all's thoughts on it.

I.e., should we break it into a separate section with its own code block, or is this fine as is?

### CODE REVIEW

**Comment by hawkins** [comment]
@tkh44 Is this waiting on something, i.e. is there anything I can do to help this get merged in? 😃

**Comment by tkh44** [comment]
I'm waiting to see if this limitation is going to be present in v7 😄

**Comment by tkh44** [comment]
image
 There are still some bugs but it is almost working.

**Comment by hawkins** [comment]
Oh rad! That's great news! 🎉

**Comment by hawkins** [comment]
So has this limitation been removed for v7, making this PR obsolete?

**Comment by tkh44** [comment]
Sorry about that. I will merge this after the checks pass.

**Comment by hawkins** [comment]
No sweat, just didn't want to leave it open if it was made obsolete! Let me know if there's anything you need me to do 👍

**Pull request merged**
