### PR TITLE
Add eslint plugin

### PR DESCRIPTION
**Pull request by alex-pex**
**What**: An Eslint plugin, to enforce coding style. You can choose between strings or objects.

**Why**: Emotion allow developers to write styles the way they want, without enforcing a specific coding style. In a large project, it can be useful to have an opiniated way of writing styles.

**How**: They were implemented on my big project (which was using lerna), and migrated to the fork. I used the CLI (yeoman I think) to generate the template of the eslint plugin, then TDD with code samples. It works perfectly for my project, I hope it will match your expectations ;)

**Checklist**:
- [x] Documentation
- [x] Tests
- [x] Code complete

https://github.com/alex-pex/emotion/blob/7db2475846bd752d142630ceee6d26152869708e/packages/eslint-plugin-emotion/README.md

### CODE REVIEW

**Comment by tkh44** [comment]
Use something along the lines of `object` and `string` rather than the names of 2 other libraries or use something very explicit like:

`prefer-object-styles` and/or `prefer-string-styles`

Is something like this possible?

**Comment by alex-pex** [comment]
I rewrote the plugin, mentionning "string" and "object" instead of "styled-components" and "glamorous"

**Comment by tkh44** [comment]
This looks great! Thank you for your contribution.

**Comment by alex-pex** [comment]
Everything seems ok, do you wait something before merging ? (Need to try the plug-in by yourself ?)

**Comment by alex-pex** [comment]
I rebased the PR based on the latest working commit on master (1ecb2bcd01f17421434e99ed55d93ce469935e28)

This commit broke the CI tests : https://github.com/emotion-js/emotion/commit/f689508b279e51c7bb7e7ae9030ab87af3d8c76f

**Comment by alex-pex** [comment]
I fixed the errors in https://github.com/emotion-js/emotion/pull/590

**Comment by tkh44** [comment]
Thank you for taking care of #590. I haven't had any time to dig in more than a few min.

**Comment by nsheaps** [comment]
@tkh44 what is the timeline on getting this package published to NPM?

**Comment by alex-pex** [comment]
@nsheaps v9.1.0 seems to include eslint-plugin-emotion, but the changelog doesn't mention it

**Pull request merged**
