### PR TITLE
Fix react-emotion typing

### PR DESCRIPTION
**Pull request by Ailrun**
**What**: Fixing react-emotion typing

**Why**: Current typing is redundant.

**How**: Using `create-emotion-styled` typing

**Checklist**:
- [N/A] Documentation
- [x] Tests
- [x] Code complete

I will send a PR for fixing typescript document after this PR is merged.

### CODE REVIEW

**Comment by Ailrun** [comment]
Hm, OK. Are there any more alias I should add?

**Comment by Ailrun** [comment]
@mitchellhamilton Could I ask one question? If this is merged, when it will be published?

**Comment by Ailrun** [comment]
@mitchellhamilton Please let me know the problem of (or your opinion about) this PR.
I'd like to see this typings in following release.

**Comment by epeli** [comment]
Just tested this PR on my project. Looks good to me and fixes #672 nicely. Thank you!

Eagerly waiting for the release :)

**Pull request merged**
