### PR TITLE
#1135 cache `createElement`, and make `jsx` to use as polyfill

### PR DESCRIPTION
**Pull request by morlay**

### CODE REVIEW

**Comment by mitchellhamilton** [comment]
I'm not a fan of doing this since it could cause unexpected side effects if a package that you're using internally uses a prop named css and I believe overwriting createElement might not work with `import * as React from 'react'`(I'm not totally sure on that though) and our intended solution for applying the css prop in a whole app is https://www.npmjs.com/package/@emotion/babel-preset-css-prop

**Comment by morlay** [comment]
@mitchellhamilton.
it works well for `import * as React from 'react'`, because now `react` exports `React` as namespace which is just an object.

i tried `@emotion/babel-preset-css-prop`, but as a typescript user, i have to use babel too :-(

**Comment by morlay** [comment]
@Andarist 
this PR not change the way of emotion, just make it could be hackable (we will hack `createElement` when we need). 
event in the future, react start to use ESM, these changes still working

**Comment by Andarist** [comment]
The changes from this PR will work, but what you have proposed in your issue:
```js
import React from "react"
import { jsx } from "@emotion/core"

React.createElement = jsx
``` 
won't work in the future (because of namespaces being frozen)

**Comment by morlay** [comment]
@Andarist 
I understand this point. I will remove it in future too, but now

in my case, I'm migrating my projects from `glamor` to `emotion` by replacing `{...css(` to `css={` directly.
I just wan't to simple way to make emotion work in my projects.

Maybe someone have similar issue. just hope this PR could be merged for those developer like me.

Btw I already locate why my projects is broken when using the `babel-preset-css-prop`.
https://github.com/emotion-js/emotion/issues/1147

So, it's fine to close this PR.

Thanks ~

**Pull request closed without merging**
