### PR TITLE
Amended docs to highlight there are 2 approaches to SSR

### LINKED ISSUE #1178: Problems surrounding SSR injection of <style> and unreliability of :first-child selectors
**Problem description:**

In emotion v10+, a new warning is thrown if you use `:first-child`, `:nth-child`, or `:nth-last-child` selectors in a styled component or css prop value. This is because, when using SSR, the `style` element is injected immediately above (prepended) the associated component. ([More details](https://github.com/emotion-js/emotion/issues/898).)

There are a number of problems with this approach:

> _Note: I made a [test case demo](https://codepen.io/anon/pen/BvMjeQ) to illustrate which selectors are unreliable._

1. In [our codebase](https://github.com/mineral-ui/mineral-ui/) and matching years of experience for myself and peers, the "first" selectors are used much more often than the "last". Making these selectors unreliable is a big blow to those expecting standard CSS features to work.
1. The suggested workaround of changing, e.g. `:first-child` to `:first-of-type`, only works if _all_ sibling elements are of the same type. This is probably fairly common for components like lists, grids, etc... But it's far from a guaranteed solution. It could also discourage the use of semantic markup by driving devs to "just use divs" for everything, since it's a simpler "fix".
1. The [list of unsafe selectors](https://github.com/emotion-js/emotion/blob/master/packages/cache/src/index.js#L208) is incorrect.
    - The adjacent sibling pattern, `* + [anything]`, is unreliable, but not listed.
      - This [type of selector](https://alistapart.com/article/axiomatic-css-and-lobotomized-owls) may seem somewhat obscure, but it can be rather useful.
    - `:only-child` is unreliable, but not listed.
    - `:nth-last-child` is still reliable when prepending the `style` element and should not be listed.
1. Consumers not interested in SSR should be able to turn off the warning (#1105)

**Suggested solution:**

Let's tackle each problem, in turn:

1. "First" vs. "last" selectors (or prepending vs. appending the `style` element)

    If emotion injected the `style` element _after_ (appended) the associated component, then the following selectors would be unreliable: `:last-child`, `:nth-last-child`, `:only-child`.

    Compare that to the currently unreliable selectors: `* + [anything]`, `:first-child`, `:nth-child`, `:only-child`.

    By changing to appending the `style` element, emotion would no longer block use of the common adjacent sibling selector and the "last" (rather than "first") varieties of the selectors would be affected, which I would argue is a better tradeoff more in line with actual usage of each [citation needed].

1. "of-type" workaround

    The warning's suggestion should be reworded to make clear that it may not work in all scenarios.
  
1. Incorrect unsafe list of selectors

    - `:only-child` needs to be added (changing this to `:only-of-type` is a good workaround, though!
    - If the `style` element remains prepended
      - The `* + [anything]` selector pattern needs to be flagged
      - `:nth-last-child` needs to be removed
    - If the `style` element is appended
      - Update list to include selectors in (1), above.

1. Mute the unsafe selectors warning

    At the very least, emotion should allow consumers to do so.

**Alternative solutions:**

Another suggested workaround is to somehow replace `:first-child` selectors with `:first-child:not(style), style:first-child + *` in the styles output. While a clever bit of CSS selecting, this suggestion has two main problems I can think of: 1) it won't work for non-`:first-child` selectors (though maybe we could come up with other rewrites for the others) and 2) replacing `:first-child` in a selector is not trivial, as it is affected by whether or not its used on the immediate element being styled or a descendent element.

The maintainers of emotion and its community could also simply decide that making these selectors unreliable is not worth the tradeoff of SSR "just working" and abandon the approach of injecting colocated `style` elements entirely. I have no idea how palatable such a change would be, but wanted to enumerate all the options.

-----

This issue is intended to open discussion around these problems. If we can decide on forward actions, I'm happy to help implement wherever I can.

### PR DESCRIPTION
**Pull request by JakeGinnivan**
Also do not warn about nth child selectors if using direct API integrations.

Opening this as a discussion on how to fix #1178. 

I have a question though which will help me finish this PR off properly, I really do not understand the section in the docs with the CacheProvider for migration, if you do this you end up with 2 versions of the cache, the one which is created automatically and the one I create. This would not work with the fix I have implemented afaik?

// @mitchellhamilton

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
More than happy to have a quick skype/slack call to discuss the changes.

**Comment by JakeGinnivan** [comment]
Hey @mitchellhamilton thoughts on this approach.

Would need a hand doing tests.

**Comment by mitchellhamilton** [comment]
I'm mostly fine with the code change(there is technically the problem that users of renderStylesTo(String|NodeStream) won't see the message when it's valid for them but I think that's acceptable). For tests, write something like https://github.com/emotion-js/emotion/blob/3672d4044bbbe93b955adca5d588444e1bab983e/packages/styled/__tests__/styled-dom.js#L28-L54 in https://github.com/emotion-js/emotion/blob/master/packages/core/__tests__/compat/server.js
 
I'm uneasy with the docs changes. The primary recommendation should still be to use zero config SSR and not use the given selectors because while this is causing problems for some people, a much larger group are not having problems and by foregrounding this issue so significantly, it means people who just want to know how to get started with emotion have to make even more decisions. Using the emotion-server APIs should be aimed at people who have significant codebases using these selectors and don't want to migrate or want to delay migrating, it shouldn't be recommended for new code(if people really want to use it that way, they can still do that, I'm not aiming to stop that).

While, yes, this is restricting what consumers of emotion can do with css, I don't think that's inherently a bad thing, a significant part of the point of emotion and other css in js libraries is to exactly that by stopping people from writing class names themselves and IMO this is a similar thing, by applying a constraint, we're able to create something that is helpful is a huge way(I know the impact will differ from person to person but personally it's been hugely helpful for me).

**Comment by JakeGinnivan** [comment]
Appreciate the response. 

> The primary recommendation should still be to use zero config SSR and not use the given selectors because while this is causing problems for some people, a much larger group are not having problems and by foregrounding this issue so significantly

I don't mind pushing people towards the zero-config but they should be aware of the trade offs they are making.

> While, yes, this is restricting what consumers of emotion can do with css, I don't think that's inherently a bad thing

I kinda disagree with this point, CSS in JS gives a heap of stuff but nth selectors are really really useful part of CSS and it was really unexpected for it to just not work. @mandymichael may be able to elaborate on this better than I can

**Comment by davidkpiano** [comment]
> While, yes, this is restricting what consumers of emotion can do with css, I don't think that's inherently a bad thing

A styling SSR strategy that does not render styles **exactly the same** as it would without SSR is an SSR strategy that 🚫 **does not work** 🚫. Full stop.

It doesn't matter if it works for most people/apps and not for others. If it doesn't work for 100% of enabled use-cases, is not a workable strategy.

If https://github.com/emotion-js/emotion/issues/1178 won't be resolved another way (which it should be), I strongly believe this _needs_ to be included in the documentation, or hours will be wasted trying to figure out an alternate SSR strategy or refactoring their styles in a less-than-desirable way (all the ways listed in #1178).

**Comment by JakeGinnivan** [comment]
I have opened https://github.com/emotion-js/emotion/pull/1483 to get the warning fixed, will make another pass at the docs and remove code changes in this PR tomorrow

**Comment by JakeGinnivan** [comment]
Going to open a new PR

**Pull request closed without merging**
