### PR TITLE
Documentation Updates

### PR DESCRIPTION
**Pull request by joebell93**
**What**:
Added a tiny line to the top of the README to direct consumers to the migration guide.

**Why**:
Although I've been keeping tabs on Emotion 10, as an Emotion 9 user, I was surprised that [emotion.sh](https://emotion.sh/) suddenly updated its docs. First thing I did was head to the README and try to find the migration guide, I think it would be really handy to stick this link at the top for any other Emotion 9 (or earlier) users.

**How**: with my fingers and a keyboard 💃  (edited some markdown)

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Code complete

Side note: thanks to all of the maintainers for your hard work, you converted a CSS-in-JS sceptic and I have massive respect for what you're trying to achieve with this project. Thank you!
I've been trying to write some methodology/guidelines for structuring CSS-in-JS projects for some time (currenly updating) and would appreciate any eyes on that too: https://github.com/joebell93/smoothie

### CODE REVIEW

**Comment by CodeWitchBella** [comment]
AFAIK the codemoddable css example is not wrong - there is css export from emotion for compatibility and it behaves differently from one the @emotion/css import. You want to change it over eventually but if you pass result of css template to className you can't just swap imports and have it work

**Comment by joebell93** [comment]
Ha my bad @CodeWitchBella, you're totally right! I'll keep this PR to the README update

**Comment by joebell93** [comment]
@mitchellhamilton @Andarist just updated with `master`, would it be ok to merge? Thank you

**Comment by Andarist** [comment]
Thanks!

**Comment by tkh44** [comment]
Thanks @joe-bell

**Pull request merged**
