### PR TITLE
fix: flow type error

### PR DESCRIPTION
**Pull request by FezVrasta**
**What**:

fix for #1125

**Why**:

refer to #1125

**How**:

Fixes the emotion cache context types

**Checklist**:

- [ ] Documentation "N/A"
- [ ] Tests "N/A"
- [x] Code complete

### CODE REVIEW

**Comment by FezVrasta** [comment]
linting is failing for some reason, the syntax is correct tho.

I can put that into a Flow declaration comment to avoid the linting error if it's fine to you.

**Comment by MrBenJ** [comment]
Hello!

I'm interested in helping out with this particular issue. Is there anything I can do to assist?

**Comment by FezVrasta** [comment]
It seems to have been merged with the linked pr

**Comment by MrBenJ** [comment]
Ahh, I see it. Looks like it was merged in 10 days ago and we're waiting on the next release (last was 23 days ago). Thanks @FezVrasta !

**Comment by Andarist** [comment]
@MrBenJ The new release is out.

**Pull request closed without merging**
