### PR TITLE
Add third party packages section to document

### LINKED ISSUE #638: Documenting Ember add-on
I've written an Ember add-on to integration Emotion into Ember apps, called [`ember-emotion`](https://www.npmjs.com/package/ember-emotion). I would love to add it to the documentation so that people in the Ember community know that it's an option when looking at Emotion's website.

Would you be interested in me adding it to the *Packages* section of the documentation site even though it isn't an "official" package that's part of your organization? Would you be interested moving the repo under your umbrella?

### PR DESCRIPTION
**Pull request by Ailrun**
**What**: Documents for third party packages

**Why**: To support and encourage third party package authors.

**How**: Rename "Packages" section into "Official Packages" and add "Third Party Packages" section.

**Checklist**:
- [x] Documentation
- [N/A] Tests
- [N/A] Code complete

Resolves #638.

### CODE REVIEW

**Comment by Ailrun** [comment]
What is that weird error? Why couldn't it find a `handlebar`?

**Comment by Ailrun** [comment]
@mitchellhamilton Ah, his document use `handlebars`... I miss that part. I will fix that.

**Comment by Ailrun** [comment]
@mitchellhamilton It still emits a same error. Where do I need to add `handlebars` related import (or settings, ...)?

**Comment by mitchellhamilton** [comment]
I've been thinking about this and I'm not sure if it's a good idea because if we add the documentation for one package then we have to add the documentation for every package that wants it and it's effectively saying we recommend whatever packages that are there.

I think a better solution is to add a top level Community page, add it to the links at the top and have the contents be from [emotion-js/awesome-emotion](https://github.com/emotion-js/awesome-emotion) which I just created, similar to https://www.styled-components.com/ecosystem.

**Comment by Ailrun** [comment]
@mitchellhamilton Wow, awesome opinion! Thank you for making that page. However, I wish that there is a link to your repository from our site. Is it OK for you?

**Comment by mitchellhamilton** [comment]
I was thinking, instead of linking to it, embed the contents of it in the site.

**Comment by Ailrun** [comment]
@mitchellhamilton All contents? Just like styled component did?

**Comment by Ailrun** [comment]
Close this in favor of #720.

**Pull request closed without merging**
