### PR TITLE
Align table columns

### PR DESCRIPTION
**Pull request by ravinggenius**
**What**:

Consistently align table columns on https://emotion.sh/docs/babel-plugin-emotion.

**Why**:

I had a hard time understanding the first few rows on the documentation site. (GitHub does manage to show the table columns correctly.)

**How**:

I added a bunch of space characters and a few pipes using GitHub's online editor.

**Checklist**:

- [x] Documentation
- [x] Tests N/A
- [x] Code complete N/A

---

I was reading through the documentation site to try to determine how much trouble it would be to use emotion with [express-react-views](https://github.com/reactjs/express-react-views). I don't need any client-side rendering features; do you think emotion would be a poor fit?

### CODE REVIEW

**Comment by ravinggenius** [comment]
Not to be impatient, but this change fixes a real eyesore on the documentation website and is also about the most innocuous change I can think of (apart from a simple typo fix). Please merge it, or if I got something wrong, please let me know.

**Comment by mitchellhamilton** [comment]
@ravinggenius Sorry I haven't responded to this and thanks for the PR!! [It doesn't look like this fixed it, on the deploy preview the columns aren't aligned](https://deploy-preview-592--emotion.netlify.com/docs/babel-plugin-emotion)

**Comment by ravinggenius** [comment]
Okay I have to admit I'm a bit surprised that didn't work, but thanks for the feedback. I'll pull down the repo and get it working in a local preview.

**Comment by ravinggenius** [comment]
I did some research, and found an [open issue in Remark](https://github.com/remarkjs/remark/issues/320), which Gatsby uses to parse Markdown. Until that can be fixed, I manually converted the table to HTML.

I also rebased my branch onto `master`.

**Pull request merged**
