### PR TITLE
Improved docs around SSR apis

### LINKED ISSUE #1178: Problems surrounding SSR injection of <style> and unreliability of :first-child selectors
**Problem description:**

In emotion v10+, a new warning is thrown if you use `:first-child`, `:nth-child`, or `:nth-last-child` selectors in a styled component or css prop value. This is because, when using SSR, the `style` element is injected immediately above (prepended) the associated component. ([More details](https://github.com/emotion-js/emotion/issues/898).)

There are a number of problems with this approach:

> _Note: I made a [test case demo](https://codepen.io/anon/pen/BvMjeQ) to illustrate which selectors are unreliable._

1. In [our codebase](https://github.com/mineral-ui/mineral-ui/) and matching years of experience for myself and peers, the "first" selectors are used much more often than the "last". Making these selectors unreliable is a big blow to those expecting standard CSS features to work.
1. The suggested workaround of changing, e.g. `:first-child` to `:first-of-type`, only works if _all_ sibling elements are of the same type. This is probably fairly common for components like lists, grids, etc... But it's far from a guaranteed solution. It could also discourage the use of semantic markup by driving devs to "just use divs" for everything, since it's a simpler "fix".
1. The [list of unsafe selectors](https://github.com/emotion-js/emotion/blob/master/packages/cache/src/index.js#L208) is incorrect.
    - The adjacent sibling pattern, `* + [anything]`, is unreliable, but not listed.
      - This [type of selector](https://alistapart.com/article/axiomatic-css-and-lobotomized-owls) may seem somewhat obscure, but it can be rather useful.
    - `:only-child` is unreliable, but not listed.
    - `:nth-last-child` is still reliable when prepending the `style` element and should not be listed.
1. Consumers not interested in SSR should be able to turn off the warning (#1105)

**Suggested solution:**

Let's tackle each problem, in turn:

1. "First" vs. "last" selectors (or prepending vs. appending the `style` element)

    If emotion injected the `style` element _after_ (appended) the associated component, then the following selectors would be unreliable: `:last-child`, `:nth-last-child`, `:only-child`.

    Compare that to the currently unreliable selectors: `* + [anything]`, `:first-child`, `:nth-child`, `:only-child`.

    By changing to appending the `style` element, emotion would no longer block use of the common adjacent sibling selector and the "last" (rather than "first") varieties of the selectors would be affected, which I would argue is a better tradeoff more in line with actual usage of each [citation needed].

1. "of-type" workaround

    The warning's suggestion should be reworded to make clear that it may not work in all scenarios.
  
1. Incorrect unsafe list of selectors

    - `:only-child` needs to be added (changing this to `:only-of-type` is a good workaround, though!
    - If the `style` element remains prepended
      - The `* + [anything]` selector pattern needs to be flagged
      - `:nth-last-child` needs to be removed
    - If the `style` element is appended
      - Update list to include selectors in (1), above.

1. Mute the unsafe selectors warning

    At the very least, emotion should allow consumers to do so.

**Alternative solutions:**

Another suggested workaround is to somehow replace `:first-child` selectors with `:first-child:not(style), style:first-child + *` in the styles output. While a clever bit of CSS selecting, this suggestion has two main problems I can think of: 1) it won't work for non-`:first-child` selectors (though maybe we could come up with other rewrites for the others) and 2) replacing `:first-child` in a selector is not trivial, as it is affected by whether or not its used on the immediate element being styled or a descendent element.

The maintainers of emotion and its community could also simply decide that making these selectors unreliable is not worth the tradeoff of SSR "just working" and abandon the approach of injecting colocated `style` elements entirely. I have no idea how palatable such a change would be, but wanted to enumerate all the options.

-----

This issue is intended to open discussion around these problems. If we can decide on forward actions, I'm happy to help implement wherever I can.

### PR DESCRIPTION
**Pull request by JakeGinnivan**
Fixes #1178

**What**: 2 main changes
1) Improve the docs around SSR to make it clear there is an advanced integration which does not break some CSS features.
2) ~The hydrate function is not on custom created caches which is required to remove the nth child warning when using the default cache.~ I've now removed this change, I found out about using the `data-emotion-css` attribute to automatically hydrate

**Why**:
Because it should be the users decision what trade offs they would like, do you want a really simple integration with some CSS limitations, or do you want to perform a more complex integration and remove the CSS limitations.

For us it is not acceptable to not use the nth child selectors.

**How**:

Copied the hydrate function from the create-emotion module into the createCache function

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Code complete
- [x] Changeset

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
Not sure how code coverage has decreased, I have just updated the docs

**Comment by JakeGinnivan** [comment]
@mitchellhamilton have circled back around to this. Hopefully this change is a good compromise between showing people there is a more advanced integration which removes the CSS limitations, but prevents usage of the streaming APIs.

**Comment by mitchellhamilton** [comment]
I made a couple wording changes and a little change to the code example, notably removing the client section because it's not necessary when using the default cache. Let me know what you think about the changes.

I know I've been hesitant about this but you're right that we need to call this out, thanks for this, the feedback is really appreciated. ❤️

**Comment by JakeGinnivan** [comment]
@mitchellhamilton unfortunately the client part is still needed, otherwise you get warnings in your console about unsafe selectors :(

**Comment by mitchellhamilton** [comment]
👍 added it back

**Comment by jooj123** [comment]
Thanks @JakeGinnivan @mitchellhamilton - very clear now 👍

**Comment by JakeGinnivan** [comment]
Thanks @mitchellhamilton, I think this will help a lot of people.

**Pull request merged**
