### PR TITLE
chore(lint): consistent trailing commas

### PR DESCRIPTION
**Pull request by Haroenv**
see https://github.com/emotion-js/emotion/pull/525#issuecomment-356367994

**What**: updated trailing commas

**Why**: because that's what my `eslint` screamed at

**How**:

1. ran `yarn eslint . --fix`
2. ran `yarn jest -u` (trailing commas changed snapshots)

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Code complete

### CODE REVIEW

**Comment by tkh44** [comment]
Did prettier change the rules for trailing commas? I'm trying to figure out what I missed.

**Comment by Haroenv** [comment]
ugh, now eslint is telling me to remove the trailing commas (it's probably a bug in prettier then 🤔)

**Comment by tkh44** [comment]
We have never had trailing commas. I wonder if there was a bad release somewhere in the chain of deps. I just pulled your branch and it was telling me to remove the commas 🤷‍♂️

**Comment by Haroenv** [comment]
@tkh44, feel free to remove those then, maybe I had the wrong dependencies in cache somehow 🤔 sorry for the noise

**Pull request closed without merging**
