### PR TITLE
ThemeOverride to make define custom theme type

### PR DESCRIPTION
**Pull request by morlay**
**What**:

We need to define project theme type to make theme parameters clear.

**Why**:

we could not do this by 
```ts
declare module 'react' {
  interface DOMAttributes<T> {
    css?: InterpolationWithTheme<ThemeObject>
  }
}

declare global {
  namespace JSX {
    /**
     * Do we need to modify `LibraryManagedAttributes` too,
     * to make `className` props optional when `css` props is specified?
     */

    interface IntrinsicAttributes {
      css?: InterpolationWithTheme<ThemeObject>
    }
  }
}
```

**How**:

after new changes. we could do like this.

```ts
declare module "@emotion/core" {
  export interface ThemeOverride {
    theme(): { 
       color: { primary: "#000" } 
    }; 
  }
}
```

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Code complete
- [ ] Changeset

### CODE REVIEW

**Comment by Andarist** [comment]
This has already be done for the upcoming v11. Im afraid that we cannot backport this to v10. V11 is available on npm though so i would encourage you to migrate to it

**Comment by morlay** [comment]
cool. i will migrate to the new version tomorrow 😀.

**Comment by Andarist** [comment]
Give me a ping if you encounter any problems.

**Comment by morlay** [comment]
@Andarist the way for defining type of v11 is a little dirty.

for theming, we usually define a theme object first. 
```ts
const defaultTheme = {
   fontFamily: { 
     mono: "",
     system: "",
   }, 
   ...
}
```

then got the theme type through `typeof`
```ts
type TTheme = typeof defaultTheme
```

and now we have to use this way to overwrite 
```
declare module "@emotion/react" {
  export interface Theme {
    fontFamily: TTheme["fontFamily"];
    weight: TTheme["weight"];
    size: TTheme["size"];
    color: TTheme["color"];
    zIndex: TTheme["zIndex"];
    radius: TTheme["radius"];
    spacing: TTheme["spacing"];
    shadow: TTheme["shadow"];
}
```

I prefer the way of this pr
```ts
declare module "@emotion/core" {
  export interface ThemeOverride {
    theme(): TTheme
  }
}
```

**Comment by Andarist** [comment]
Doesnt this work for you?
```ts
declare module '@emotion/react' {
  export interface Theme extends TTheme {}
}
```

**Comment by morlay** [comment]
@Andarist 
it will not work.
typeof object is type，not interface. so not be extendable.

sorry for replaying late. busying with Chinese New Year

**Comment by Andarist** [comment]
> sorry for replaying late. busying with Chinese New Year

No problem :)

> typeof object is type，not interface. so not be extendable.

Can't you do something like this?
```ts
type TTheme = typeof defaultTheme

interface ITTheme extends TTheme {}

declare module '@emotion/react' {
  export interface Theme extends ITTheme {}
}

```

**Comment by morlay** [comment]
@Andarist 
Sorry, I hold old context about `TS2312: An interface may only extend a class or another interface.`.
TypeScript team upgrade it since version 2.2. 
Now only `typeof` literal value (`1`, `true`, `"v"`...) has the limits.
object `{}`, array `[]`, even `new String()`,`new Boolean()` could be extendable. 

So the first way will be work too.

```ts
const defaultTheme = {} 

type TTheme = typeof defaultTheme

declare module '@emotion/react' {
  export interface Theme extends TTheme {}
}
```

Thanks

**Pull request closed without merging**
