### PR TITLE
chore: upgrade to babel-plugin-emotion

### LINKED ISSUE #515: Upgrade to babel-plugin-macros
The project was renamed from `babel-macros` to `babel-plugin-macros` to better support babel v7. No other breaking changes.

### PR DESCRIPTION
**Pull request by Haroenv**
I didn't do __extensive__ testing, but the tests pass and @kentcdodds said there were no breaking changes…

fixes #515

**What**: changed `babel-macros` to `babel-plugin-macros`

**Why**: this is the new name and the one that is going to be incorporated in CRA

**How**: pretty much find and replace `babel-macros` for `babel-plugin-macros`

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Code complete

### CODE REVIEW

**Comment by Haroenv** [comment]
The tests completely fail on my end because eslint (prettier) expects trailing commas, while they seem to be explicitly forbidden over the code base

**Comment by tkh44** [comment]
Thanks @Haroenv I'll look at that right now.

**Comment by Haroenv** [comment]
tests are failing on CI because of unrelated linting, AFAICT #526 should fix that

**Comment by Haroenv** [comment]
voilà, now without the accidental trailing commas @tkh44 🤷‍♂️

**Comment by tkh44** [comment]
Thanks again

**Comment by Haroenv** [comment]
With pleasure, glad @kentcdodds made it such a smooth upgrade path

**Comment by tkh44** [comment]
Is there anything else you would like to release with this @mitchellhamilton? Should we backport this to 8? or just run with putting it in 9?

**Comment by Haroenv** [comment]
I just saw the commit message said emotion, but that should have been macros

**Comment by mitchellhamilton** [comment]
@tkh44 Let's just put it in 9 since AFAIK macros built with `babel-macros` are compatible with `babel-plugin-macros`.

Maybe @kentcdodds can correct me if I'm wrong?

We could do a release now with this and #516 to next.

**Comment by kentcdodds** [comment]
Yes, it should actually be totally compatible. All macros using `babel-macros` to be created should work with the `babel-plugin-macros` transform because the creation just sets a few properties on your function so it should work :)

**Pull request merged**
