### PR TITLE
Add toHaveStyleRule support for React Native

### LINKED ISSUE #1790: document is not defined when using jest-enzyme with React Native
**Current behavior:**

Asserting `toHaveStyleRule` on a `shallow` rendered React Native component will fail with error `ReferenceError: document is not defined` 

**To reproduce:**

1. Create component:
```jsx
import React from 'react';
import styled from '@emotion/native'

const Container = styled.View`
  height: 100px;
  width: 100px;
`;

const MyComponent = () => <Container />;

export default MyComponent;
export { Container };
```
2. create test:
```jsx
import React from 'react';
import { matchers } from 'jest-emotion';
import { shallow } from 'enzyme'
import MyComponent, { Container } from './MyComponent';

expect.extend(matchers);

describe('<MyComponent />', () => {
  it('should have height 100', () => {
    const wrapper = shallow(<MyComponent />);
    expect(wrapper.find(Container)).toHaveStyleRule('height', '100px');
  });
});
```

**Expected behavior:**

`toHaveStyleRule` should pass.

**Environment information:**

- `react` version: `16.9.0`
- `react-native` version: `0.61.5`
- `@emotion/core` version: `^10.0.28`
- `@emotion/native` version: `^10.0.27`
- `jest-emotion` version: `^10.0.27`

### PR DESCRIPTION
**Pull request by MrCreeper1008**
Closes #1790

**What**:  
Currently, `toHaveStyleRule` is having issue with React native.

**Why**:
React Native components do not have `className` prop which this rule relies on to perform checks. Instead, they have a `style` prop which takes a style object. However, when `@emotion/native` is used with React Native components, the original components are nested 3 levels deep, making the `style` prop inaccessible unless we `dive`.

**How**:
By `dive`ing into the received component three times, the `style` prop is exposed, which allows us to perform checks. However, style checking for React Native components is implemented differently, so I added a `native` option. To use,
```javascript
expect(ReactNativeComponent).toHaveStyleRule('flexDirection, 'row', { native: true });
```
Alternatively, we can create a native version of `jest-emotion`:
```javascript
import { matchers } from 'jest-emotion/native';
```

**Checklist**:
- [ ] Documentation
- [ ] Tests
- [ ] Code complete
- [x] Changeset 

**Caveats**
- This fix is mainly geared towards components shallowly rendered with `enzyme`, so I have no idea if this would work with other testing libraries like `native-testing-library`.
- Also, I have no idea how to test this. (Do we install `react-native` just to get a couple components for us to test with?)  

I would appreciate any feedback given to this PR!

Edit: Add usage details.  
Edit 2: Link to issue

### CODE REVIEW

**Comment by MrCreeper1008** [comment]
Sorry for screwing up the commit history a bit.

**Comment by MrCreeper1008** [comment]
@Andarist I don't think having a `/enzyme/native` entry point is a good idea, since this should also work with `native-testing-library`, so doesn't make sense to have it under `/enzyme`.

**Comment by Andarist** [comment]
@MrCreeper1008 do you think this should be a part of a new `@emotion/jest/native` entrypoint? or should it be just a part of the "core" `toHaveStyleRule` (like it is now)?

**Comment by MrCreeper1008** [comment]
I think creating a new entry point makes more sense. React Native projects will be only using the native version of `toHaveStyleRule` anyway, so passing `{ native: true }` to it creates unnecessary noise. Developers can choose to alias `@emotion/jest/native` to `@emotion/jest` if they find the extra entry point annoying.

**Comment by Andarist** [comment]
1. Would you be willing to implement the required changes?
2. Have you tested this in any RN project? Are you confident that this is working for the most common cases?

**Comment by MrCreeper1008** [comment]
1. I'd be more than happy to implement the change. But just to be clear, can you list out all the changes you want?  
2. I created a new react native project to test this out and everything seems to be working fine.

**Comment by Andarist** [comment]
Please add `/native` entry point by adding it [here](https://github.com/emotion-js/emotion/blob/4d3b60d0d448a61d762ee150e6cb7a2c995ccc2f/packages/jest/package.json#L62) and creating a file like [this](https://github.com/emotion-js/emotion/blob/4d3b60d0d448a61d762ee150e6cb7a2c995ccc2f/packages/jest/serializer/package.json). The source code for this entry should look similar to this one: https://github.com/emotion-js/emotion/blob/4d3b60d0d448a61d762ee150e6cb7a2c995ccc2f/packages/jest/src/index.js . Technically there might also be a need for native serializer, right? But not sure if you want to work on it as well. If not - then this should only export `matchers`.

**Comment by MrCreeper1008** [comment]
Can you elaborate more on the need for serializer? Is it used for snapshot testing?

**Comment by Andarist** [comment]
Yes, exactly.

**Comment by MrCreeper1008** [comment]
Shouldn't be hard to implement the serializer. I think I can handle it.

**Comment by MrCreeper1008** [comment]
@Andarist is this structure you're aiming for?

**Comment by Andarist** [comment]
Yes, pretty much - need to review more closely later, especially around extending global `jest` types etc, but looks good at the first glance.

**Comment by MrCreeper1008** [comment]
Thank you. I'll start implementing the serializer.

**Pull request closed without merging**
