### PR TITLE
feat(babel-preset-css-prop): option cssPropOnly #1794

### PR DESCRIPTION
**Pull request by morlay**
**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Code complete
- [ ] Changeset

### CODE REVIEW

**Comment by morlay** [comment]
@Andarist 

case like below may just notice in document. "when cssPropOnly enabled, don't use like this."
```
const props = { css: { color: 'hotpink' } }
;<div {...props}/>
```

**Comment by Andarist** [comment]
I would like [this PR](https://github.com/babel/babel/pull/11154) to get merged into Babel before we proceed any further with this.

**Comment by Andarist** [comment]
This is not something that we'd like to get in right now but is **maybe** something we'd consider in the future. For now, you have been the only user asking for it, so we don't consider this a high priority feature. We might revisit this when we upgrade to using those automatic JSX transforms introduced by Babel and React team. We are postponing working on this though as, for example, TypeScript has not yet implemented a similar feature.

**Comment by morlay** [comment]
@Andarist 
it's ok. i have switch to my custom [babel plugin](https://github.com/querycap/webappkit/tree/master/%40querycap-ui/babel-preset-css-prop) to do this.

btw. how about the v11?

**Pull request closed without merging**
