### PR TITLE
Fix Theme import for newer Typescript module resolution modes

### LINKED ISSUE #3092: Typescript typing issue with themes when using "Bundler" module resolution
**Current behavior:**
When using Typescript 5 with `"moduleResolution": "Bundler"`,  the typing
for the `css` prop is not working properly, particularly with the theme type.
I have followed the documentation to override the Theme type including
using the following directive:
```
/// <reference types="@emotion/react/types/css-prop" />
```
Typescript complains with an error like:
```
ERROR in src/App.tsx:20:20
TS7006: Parameter 'theme' implicitly has an 'any' type.
    18 |   return (
    19 |     <div className={appClassName}>
  > 20 |       <Title css={(theme) => ({ color: theme.headerColor })}>
       |                    ^^^^^
    21 |         Emotion Issue Template
    22 |       </Title>
    23 |
```

**To reproduce:**

1. Clone [this repo](https://github.com/kyvong/emotion-issue-template-forked/tree/main). The repo is based off the CodeSandbox
issue template.
2. Run `npm install && npm run start`

**Expected behavior:**
There should be no type error.  The type for the `theme` parameter should be the overridden one provided in the project.

The issue is resolved by making the following change in [css-prop.d.ts](https://github.com/emotion-js/emotion/blob/main/packages/react/types/css-prop.d.ts#L3)
```
--- a/packages/react/types/css-prop.d.ts
+++ b/packages/react/types/css-prop.d.ts
@@ -1,6 +1,6 @@
 import {} from 'react'
 import { Interpolation } from '@emotion/serialize'
-import { Theme } from '.'
+import { Theme } from '@emotion/react'
```

It also looks like a similar change should be made to [jsx-namespace.d.ts](https://github.com/emotion-js/emotion/blob/main/packages/react/types/jsx-namespace.d.ts)
```
--- a/packages/react/types/jsx-namespace.d.ts
+++ b/packages/react/types/jsx-namespace.d.ts
@@ -1,6 +1,6 @@
 import 'react'
 import { Interpolation } from '@emotion/serialize'
-import { Theme } from './index'
+import { Theme } from '@emotion/react'
```

**Environment information:**

- `Typescript` version: 5
- `@emotion/react` version: 11.11.1

### PR DESCRIPTION
**Pull request by kyvong**
**What**:
Fix #3092

**Why**:

**How**:
Update import statements

**Checklist**:

- [ ] Documentation NA
- [ ] Tests NA
- [x] Code complete
- [x] Changeset

### CODE REVIEW

**Comment by kyvong** [comment]
Is there any additional information I could provide to help get this considered for approval?  This is a 2 line change in the import statements.  This self referencing import is already used in the code, e.g. https://github.com/emotion-js/emotion/blob/f3b268f7c52103979402da919c9c0dd3f9e0e189/packages/react/types/theming.d.ts#L5

**Comment by Andarist** [comment]
I'll try to review your repro case next week.

**Comment by bryanph** [comment]
@Andarist Any chance this can be merged soon?

**Comment by kyvong** [comment]
@emmatown maybe you could help review this since it looks like you worked on similar issues with "bundler" module resolution before.  It is only a 2 line change.

**Review by emmatown — APPROVED** [review]

**Pull request merged**
