### PR TITLE
[WIP] Enable TS tests on CI

### PR DESCRIPTION
**Pull request by Andarist**
TODO: Need to write a script which runs this script only if it's present in package.json of a particular package

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
I am fixing all the tests in #1501. Will put this into that PR if you want

**Comment by Andarist** [comment]
@JakeGinnivan yeah - would be great

**Comment by JakeGinnivan** [comment]
@Andarist tests are green on #1501. This can probably be closed now

**Comment by Andarist** [comment]
Super cool, thanks!

**Pull request closed without merging**
